container: "mkv"

video:
  target: "h264_8bit"

audio:
  # Formats considered ideal that do NOT require conversion
  acceptable:
    - aac
    - eac3
    - flac
  
  # Conversion rules if the original codec is not listed above
  mappings:
    ac3:
      target: "eac3"
    dts:
      target: "eac3"
    alac:
      target: "flac"
    default:
      target: "aac"